export const CREATE_BOOKING = "CREATE_BOOKING";
export const GET_BOOKING = "GET_BOOKING";
export const GET_BOOKING_LIST = "GET_BOOKING_LIST";
export const UPDATE_BOOKING = "UPDATE_BOOKING";
export const DELETE_BOOKING = "DELETE_BOOKING";
